HSU-Likelion12-yourSide/YourSide-Server

yourside/src/main/java/com/likelion/yourside/domain/Bookmark.java
yourside/src/main/java/com/likelion/yourside/domain/Comment.java
yourside/src/main/java/com/likelion/yourside/domain/Notation.java
yourside/src/main/java/com/likelion/yourside/domain/Posting.java

- close #14 
1. Change Entity name
2. Change Package Name

🩹 Change Entity name

---

yourside/src/main/java/com/likelion/yourside/domain/Posting.java
yourside/src/main/java/com/likelion/yourside/domain/Worksheet.java

- close #16 
1. Posting Table Image Field 제거
2. Worksheet Table Image Field 제거

🔒️ Delete Image Field

---

yourside/src/main/java/com/likelion/yourside/user/controller/UserController.java
yourside/src/main/java/com/likelion/yourside/user/repository/UserRepository.java
yourside/src/main/java/com/likelion/yourside/user/service/UserService.java
yourside/src/main/java/com/likelion/yourside/user/service/UserServiceImpl.java

- close #18 
1. UserController 생성
2. UserService 생성
3. UserRepository 생성

User 기본 세팅

---

yourside/src/main/java/com/likelion/yourside/user/controller/UserController.java
yourside/src/main/java/com/likelion/yourside/user/service/UserService.java
yourside/src/main/java/com/likelion/yourside/user/service/UserServiceImpl.java

- close #22 
1. username 중복 여부 조회 API 개발
2. API Test

[로그인 페이지] username 중복 여부 조회

---

.idea/.gitignore
.idea/YourSide-Server.iml
.idea/compiler.xml
.idea/gradle.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml

controller, repository, service 패키지 생성
- close #30 
natation 기본 세팅

✨ Notation 패키지 기본 설정

---

yourside/src/main/java/com/likelion/yourside/user/dto/UserCheckPasswordResponseDto.java
yourside/src/main/java/com/likelion/yourside/user/dto/UserCheckUsernameResponseDto.java
yourside/src/main/java/com/likelion/yourside/user/dto/UserLoginResponseDto.java
yourside/src/main/java/com/likelion/yourside/user/service/UserServiceImpl.java

- close #36 
1. 로그인 , 아이디 & 비번 조회 ResponseBody 형식 수정

[로그인] ResponseBody 수정

---

.idea/compiler.xml
.idea/workspace.xml
yourside/src/main/java/com/likelion/yourside/notation/controller/NotationController.java
yourside/src/main/java/com/likelion/yourside/notation/dto/NotationDto.java
yourside/src/main/java/com/likelion/yourside/notation/dto/NotationListDto.java
yourside/src/main/java/com/likelion/yourside/notation/repository/NotationRepository.java
yourside/src/main/java/com/likelion/yourside/notation/service/NotationService.java
yourside/src/main/java/com/likelion/yourside/notation/service/NotationServiceImpl.java
yourside/src/main/resources/application.properties

- close #34 
공지사항 전체 조회 / 공지사항 세부 조회 API 구현했습니다.
1. 공지사항 전체 조회
- 200 (조회 성공)
- 404 (찾을 수 없음)
(GET, http://localhost:8080/api/notation/list 으로 접근했습니다)
2. 공지사항 세부 조회
- 200 (조회 성공)
- 404(찾을 수 없음)

✨ 공지사항 관련 API 구현

---

yourside/src/main/java/com/likelion/yourside/notation/controller/NotationController.java

공지사항 API 확인을 위해 공지사항 더미 데이터를 데이터베이스에 추가함
- close #38 
mySQL에 기디측에서 올려주신 공지사항 더미 데이터 추가함

📝 공지사항 더미데이터 추가

---

yourside/src/main/java/com/likelion/yourside/worksheet/controller/WorksheetController.java
yourside/src/main/java/com/likelion/yourside/worksheet/dto/WorksheetGetAllListResponseDto.java
yourside/src/main/java/com/likelion/yourside/worksheet/dto/WorksheetGetOneResponseDto.java
yourside/src/main/java/com/likelion/yourside/worksheet/repository/WorksheetRepository.java
yourside/src/main/java/com/likelion/yourside/worksheet/service/WorksheetService.java
yourside/src/main/java/com/likelion/yourside/worksheet/service/WorksheetServiceImpl.java

- close #41 
1. 결과지 전체 & 세부 조회
2. 결과지 전체 & 세부 조회 TEST

[ 내 근로 정리] 결과지 전체 & 세부 조회

---

yourside/src/main/java/com/likelion/yourside/worksheet/service/WorksheetServiceImpl.java

- close #41 
1. 결과지 전체 & 세부 조회
2. 결과지 전체 & 세부 조회 TEST

[ 내 근로 결과지 ] 결과지 전체 & 세부 조회

---

yourside/src/main/java/com/likelion/yourside/worksheet/dto/WorksheetRegisterRequestDto.java
yourside/src/main/java/com/likelion/yourside/worksheet/dto/WorksheetRegisterResponseDto.java
yourside/src/main/java/com/likelion/yourside/worksheet/service/WorksheetServiceImpl.java

- close #46 
1. Register Response & Request Dto 수정
2. Test

Worksheet - Register dto 수정

---

yourside/src/main/java/com/likelion/yourside/worksheet/service/WorksheetServiceImpl.java

- close #49 
🩹 Change worksheet getAllList 200

🩹 Change worksheet getAllList 200

---

yourside/src/main/java/com/likelion/yourside/myPage/controller/MypageController.java
yourside/src/main/java/com/likelion/yourside/myPage/dto/MypageGetworksheetlistResponseDto.java
yourside/src/main/java/com/likelion/yourside/myPage/service/MypageService.java
yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java
yourside/src/main/java/com/likelion/yourside/util/entity/BaseEntity.java
yourside/src/main/java/com/likelion/yourside/worksheet/repository/WorksheetRepository.java

- close #56 
1. 내 근로 결과지 조회 API 구현 및 테스트

[ 마이 페이지 ] 내 근로 결과지 조회 API 구현

---

yourside/src/main/java/com/likelion/yourside/domain/Posting.java
yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java
yourside/src/main/java/com/likelion/yourside/posting/controller/PostingController.java
yourside/src/main/java/com/likelion/yourside/posting/dto/PostingCreateRequestDto.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingService.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java

- close #58 
Posting 기본 세팅 및 게시글 등록 API

[ 네편 현답 ] Posting 기본 세팅 및 게시글 등록 API

---

yourside/src/main/java/com/likelion/yourside/comment/controller/CommentController.java
yourside/src/main/java/com/likelion/yourside/comment/dto/CommentCreateDto.java
yourside/src/main/java/com/likelion/yourside/comment/repository/CommentRepository.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentService.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java

- close #61 
ex) Issue 내용 간단히 기재

✨ Comment 관련 기본 세팅

---

yourside/src/main/java/com/likelion/yourside/comment/controller/CommentController.java
yourside/src/main/java/com/likelion/yourside/comment/dto/CommentCreateDto.java
yourside/src/main/java/com/likelion/yourside/comment/dto/CommentListDto.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentService.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
yourside/src/main/java/com/likelion/yourside/likes/repository/LikesRepository.java
yourside/src/main/java/com/likelion/yourside/notation/controller/NotationController.java
yourside/src/main/java/com/likelion/yourside/notation/service/NotationServiceImpl.java

- close #42 
Commit 관련 API 구현 (댓글 작성/댓글 전체 조회) + Likes Repository 생성 및 구현
**추후에 전체 조회에 "liked"가 나오는 부분 수정해야 함**

Commit 관련 API 구현 (댓글 작성/댓글 전체 조회) + Likes Repository 생성 및 구현

---

yourside/src/main/java/com/likelion/yourside/myPage/controller/MypageController.java
yourside/src/main/java/com/likelion/yourside/myPage/dto/MypageGetpostinglistResponseDto.java
yourside/src/main/java/com/likelion/yourside/myPage/service/MypageService.java
yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java

- close #65 
1. 내 질문 리스트 조회 API 구현
2. 내 질문 리스트 조회 API 테스트

[ 마이 페이지 ] 내 질문 리스트 조회 API 구현

---

yourside/src/main/java/com/likelion/yourside/bookmark/repository/BookmarkRepository.java
yourside/src/main/java/com/likelion/yourside/domain/Posting.java
yourside/src/main/java/com/likelion/yourside/posting/controller/PostingController.java
yourside/src/main/java/com/likelion/yourside/posting/dto/PostingBookmarkRequestDto.java
yourside/src/main/java/com/likelion/yourside/posting/dto/PostingCreateBookmarkRequestDto.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingService.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java

- close #67 
1. 북마크 추가 & 해제 API를 합쳐서 구현
2. Test

[ 네편 현답 ] 북마크 추가 & 해제 API 구현

---

yourside/src/main/java/com/likelion/yourside/bookmark/repository/BookmarkRepository.java
yourside/src/main/java/com/likelion/yourside/myPage/controller/MypageController.java
yourside/src/main/java/com/likelion/yourside/myPage/service/MypageService.java
yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java

- close #70 
1. 내 책갈피 조회 리스트 API 구현
2. Test

[ 마이 페이지 ] 내 책갈피 조회 리스트 API 구현

---

yourside/src/main/java/com/likelion/yourside/comment/dto/CommentListDto.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
yourside/src/main/java/com/likelion/yourside/domain/Comment.java
yourside/src/main/java/com/likelion/yourside/domain/Notation.java
yourside/src/main/java/com/likelion/yourside/domain/Posting.java
yourside/src/main/java/com/likelion/yourside/domain/Worksheet.java
yourside/src/main/resources/application.properties

- close #55 
@Column(columnDefinfition="TEXT") 추가

@Column(columnDefinfition="TEXT") 추

---

yourside/build.gradle
yourside/src/main/java/com/likelion/yourside/util/config/CorsConfig.java
yourside/src/main/java/com/likelion/yourside/util/config/SecurityConfig.java

🔒️ Add CORS Setting

---

yourside/src/main/java/com/likelion/yourside/comment/repository/CommentRepository.java
yourside/src/main/java/com/likelion/yourside/myPage/controller/MypageController.java
yourside/src/main/java/com/likelion/yourside/myPage/dto/MypageGetcommentlistResponseDto.java
yourside/src/main/java/com/likelion/yourside/myPage/service/MypageService.java
yourside/src/main/java/com/likelion/yourside/myPage/service/MypageServiceImpl.java

- close #54 
CommentCount 수정 & 내 답변 리스트 조회 API 구현

[ 마이 페이지 ] CommentCount 수정 & 내 답변 리스트 조회 API 구현

---

yourside/src/main/java/com/likelion/yourside/posting/controller/PostingController.java
yourside/src/main/java/com/likelion/yourside/posting/dto/PostingCreateResponseDto.java
yourside/src/main/java/com/likelion/yourside/posting/dto/PostingListDto.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingService.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java

- close #79 
네편현답 - 게시글 전체 조회 기능 구현하였습니다.
- 200(성공)
- 404(게시글이 존재하지 않는 경우)
- > API 명세서와 코드로 첨부하겠습니다.

✨ 게시글 전체 조회 구현

---

before switching branches
yourside/src/main/java/com/likelion/yourside/domain/Comment.java
yourside/src/main/java/com/likelion/yourside/domain/Dislikes.java
yourside/src/main/java/com/likelion/yourside/domain/Posting.java
yourside/src/main/java/com/likelion/yourside/domain/User.java
yourside/src/main/java/com/likelion/yourside/posting/controller/PostingController.java
yourside/src/main/java/com/likelion/yourside/posting/dto/PostingCreateResponseDto.java
yourside/src/main/java/com/likelion/yourside/posting/dto/PostingPopularListDto.java
yourside/src/main/java/com/likelion/yourside/posting/repository/PostingRepository.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingService.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java

- close #83 
- 인기 게시글 조회 API 구현
- 기획 수정에 따른 Entity field 추가
- 기획 수정에 따른 게시글 등록 수정(type 추가)
- 
1. 인기 게시글 조회
- test를 위한 posting 더미 데이터
- 200(조회 성공)
- 200(data 없음)
-> 흑 왜 꼭 다 끝내고 마지막에 틀린게 보이는건지 ㅠ status 404로 뜨는 부분 수정하겠습니다..
2. Entity field 추가
- comment
- dislikes
- posting
- user
3. 게시글 등록 수정

✨ 인기 게시글 조회 API 구현 & Entity field 추가 & 게시글 등록 수정(type 추가)

---

yourside/src/main/java/com/likelion/yourside/posting/controller/PostingController.java
yourside/src/main/java/com/likelion/yourside/posting/dto/PostingSearchResponseDto.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingService.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java

- close #81 
게시글 세부 조회 API 개발
- 200(해당 게시글 조회 성공)
- 404(존재하지 않음)

✨ 게시글 세부 조회 API 개발

---

yourside/src/main/java/com/likelion/yourside/comment/controller/CommentController.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentService.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
yourside/src/main/java/com/likelion/yourside/dislikes/DislikesRepository.java

- close #87 
글 싫어요 삭제 API 개발
- 200 (성공)
- 404(싫어요 한 적 없음)
- 404(해당하는 댓글 존재 x)

✨ 댓글 싫어요 삭제 API 개발

---

yourside/src/main/java/com/likelion/yourside/comment/controller/CommentController.java
yourside/src/main/java/com/likelion/yourside/comment/dto/CommentDislikeDto.java
yourside/src/main/java/com/likelion/yourside/comment/dto/CommentLikeDto.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentService.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java

- close #90 
```
댓글 좋아요/싫어요 관련 예외처리 추가
1. 추가/삭제 시 게시글을 찾을 수 없는 경우에 대한 예외처리 추가
-> 댓글을 좋아요 누르려는데 게시글이 삭제된 경우 예외가 발생할 수 있음
2. 이미 추가했는데 또 추가하는 경우에 대한 예외처리 추가
-> 이미 좋아요를 눌렀는데 또 누르게 될 수 있음
-> Likes 연관관계 스키마를 확인을 통해 구현
```
'이미 좋아요를 눌렀는데 또 누름 -> 좋아요를 이미 눌렀습니다.' 보다
'이미 좋아요를 눌렀는데 또 누름 -> 좋아요 삭제' 가 더 논리적으로 적합
1. 좋아요 관련 API
- 200(좋아요 추가 성공)
- 200(좋아요 해제 성공)
- 404(is_liked = true 로 왔는데 좋아요 한 적 없는 경우)
- 404(is_liked = false로 왔는데 이미 좋아요 한 경우)
- 404(댓글 찾을 수 없음)
- 404(게시글 찾을 수 없음)
2. 싫어요 관련 API
- 200(싫어요 추가 성공)
- 200(싫어요 해제 성공)
- 404(is_disliked = true 로 왔는데 싫어요 한 적 없는 경우)
- 404(is_disliked = false로 왔는데 이미 싫어요 한 경우)
- 404(댓글 찾을 수 없음)
- 404(게시글 찾을 수 없음)

[ 네편 현답 ] 댓글 좋아요/싫어요 관련 API 수정

---

.idea/workspace.xml
yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
yourside/src/main/java/com/likelion/yourside/domain/Comment.java
yourside/src/main/java/com/likelion/yourside/domain/User.java

- close #88 
- dislikes_count가 50개 이상일 시 해당 댓글 삭제 후 해당 Comment를 작성한 user 스키마에 delete_comments 1 증가
- delete_comments가 10이 될 시 User의 tier을 일반인으로 변경
1. 기본 세팅
- User
- Comment
2. Postman
(첫번째 댓글 삭제)
- 200(dislikes_count가 50 이상일 시 → 해당 댓글 삭제)
(삭제 후 DB 상황)
(두번째 댓글 삭제)
- 200(delete_comments가 10이 될 시→  User의 Tier을 일반인으로 변경)
(삭제 후 DB 상황)
+ 혼란을 줄 수 있을 것 같아 
`"삭제된 댓글이 10개가 되어 일반인으로 강등되었습니다." `-> 
`"(댓글 작성자의) 삭제된 댓글이 10개가 되어 일반인으로 강등되었습니다."`
으로 수정하였습니다.
+ 기존 싫어요 기능들도 잘 작동합니다

[ 네편 현답 ] 댓글 삭제 & 회원 강등 관련 API 구현

---

yourside/src/main/java/com/likelion/yourside/worksheet/controller/WorksheetController.java
yourside/src/main/java/com/likelion/yourside/worksheet/dto/WorksheetCalculateRequestDto.java
yourside/src/main/java/com/likelion/yourside/worksheet/dto/WorksheetCalculateResponseDto.java
yourside/src/main/java/com/likelion/yourside/worksheet/service/WorksheetService.java
yourside/src/main/java/com/likelion/yourside/worksheet/service/WorksheetServiceImpl.java

- close #78 
1. 결과지 계산 Logic 구현
**테스트할 더미 데이터가 없어서 테스트 못함..**

[ 내 근로 정리 ] 결과지 계산 Logic 구현

---

yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
yourside/src/main/java/com/likelion/yourside/domain/User.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java

[ 마이페이지 ] User Tier 관련 항목 수정

---

yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java
yourside/src/main/java/com/likelion/yourside/domain/Comment.java
yourside/src/main/java/com/likelion/yourside/user/service/UserServiceImpl.java

[ 네편 현답 - 댓글] 댓글 좋아요 & 싫어요

---

yourside/src/main/java/com/likelion/yourside/worksheet/service/WorksheetServiceImpl.java

🩹 Fix calculate Logic

---

yourside/src/main/java/com/likelion/yourside/domain/User.java
yourside/src/main/java/com/likelion/yourside/user/controller/UserController.java
yourside/src/main/java/com/likelion/yourside/user/dto/UserAddDummyDataRequestDto.java
yourside/src/main/java/com/likelion/yourside/user/service/UserService.java
yourside/src/main/java/com/likelion/yourside/user/service/UserServiceImpl.java

- close #103 
User Dummy 삽입 및 API 검증

[ Dummy ] User Dummy 삽입 및 API 검증

---

.idea/workspace.xml
yourside/src/main/java/com/likelion/yourside/comment/dto/CommentCreateDto.java
yourside/src/main/java/com/likelion/yourside/posting/controller/PostingController.java
yourside/src/main/java/com/likelion/yourside/posting/repository/PostingRepository.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingService.java
yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java

- close #105 
게시글 조회의 게시글 타입 필터 추가
- 200(성공)
type 0 : 네편 답변
type 1: 네편 정보

✏️ [ 네편 현답 ] 게시글 조회 - 게시글 타입 필터 추가

---

.idea/workspace.xml
yourside/src/main/java/com/likelion/yourside/comment/controller/CommentController.java
yourside/src/main/java/com/likelion/yourside/comment/dto/CommentCreateDto.java
yourside/src/main/java/com/likelion/yourside/comment/dto/CommentListRequestDto.java
yourside/src/main/java/com/likelion/yourside/comment/dto/CommentListResponseDto.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentService.java
yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java

- close #108 
-> 댓글을 작성한 유저가 해당 댓글을 좋아요/싫어요 눌렀는지 반환하는게 아닌 접속한 유저가 해당 댓글을 좋아요/싫어요 눌렀는지를 반환해주어야 함

✏️ Comment 댓글 전체 조회 관련 수정

---

yourside/src/main/java/com/likelion/yourside/domain/User.java

🩹 Fix tier

---

yourside/src/main/java/com/likelion/yourside/notation/controller/NotationController.java
yourside/src/main/java/com/likelion/yourside/notation/service/NotationService.java
yourside/src/main/java/com/likelion/yourside/notation/service/NotationServiceImpl.java

🩹 Add create Notation API

---

.idea/workspace.xml
yourside/src/main/java/com/likelion/yourside/comment/service/CommentServiceImpl.java

- close #110 
- 댓글 작성 시 해당 User가 없는 경우에 대한 예외처리 추가

✨  [ 네편 현답 ] 댓글 작성 시 해당 User가 없는 경우에 대한 예외처리 추가

---

.idea/workspace.xml
yourside/src/main/java/com/likelion/yourside/posting/service/PostingServiceImpl.java

- close #123 
게시글 등록 시 결과지를 선택하지 않은 경우에 대한 처리 추가
-> worksheet_id에 null로 들어가게 해둠

✨ 게시글 추가 - 근로결과지 선택하지 않은 경우에 대한 예외처리 추가

---

yourside/src/main/java/com/likelion/yourside/user/controller/UserController.java
yourside/src/main/java/com/likelion/yourside/user/dto/UserSignUpRequestDto.java

- close #131 
유효성 검사 로직 추가
1. DB에 null로 되어있는 nickname test1, test2... 로 채워두기
2.  유효성 검사 로직 추가
- username
- password
- email
- name
- nickname
* @NotBlank 사용
@NotBlank : Null, 빈 문자열, 스페이스만 있는 문자열 불가

♻️ [Refact] 회원가입 api - 유효성 검사 추가
